// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: tnt/tnt.proto

package tnt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TntClient is the client API for Tnt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TntClient interface {
	Insert(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Session, error)
	Get(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Session, error)
	SayHello(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Greeting, error)
}

type tntClient struct {
	cc grpc.ClientConnInterface
}

func NewTntClient(cc grpc.ClientConnInterface) TntClient {
	return &tntClient{cc}
}

func (c *tntClient) Insert(ctx context.Context, in *Session, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/main.Tnt/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tntClient) Get(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/main.Tnt/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tntClient) SayHello(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Greeting, error) {
	out := new(Greeting)
	err := c.cc.Invoke(ctx, "/main.Tnt/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TntServer is the server API for Tnt service.
// All implementations must embed UnimplementedTntServer
// for forward compatibility
type TntServer interface {
	Insert(context.Context, *Session) (*Session, error)
	Get(context.Context, *Id) (*Session, error)
	SayHello(context.Context, *Person) (*Greeting, error)
	mustEmbedUnimplementedTntServer()
}

// UnimplementedTntServer must be embedded to have forward compatible implementations.
type UnimplementedTntServer struct {
}

func (UnimplementedTntServer) Insert(context.Context, *Session) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedTntServer) Get(context.Context, *Id) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTntServer) SayHello(context.Context, *Person) (*Greeting, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTntServer) mustEmbedUnimplementedTntServer() {}

// UnsafeTntServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TntServer will
// result in compilation errors.
type UnsafeTntServer interface {
	mustEmbedUnimplementedTntServer()
}

func RegisterTntServer(s grpc.ServiceRegistrar, srv TntServer) {
	s.RegisterService(&Tnt_ServiceDesc, srv)
}

func _Tnt_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Session)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TntServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Tnt/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TntServer).Insert(ctx, req.(*Session))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tnt_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TntServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Tnt/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TntServer).Get(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tnt_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TntServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Tnt/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TntServer).SayHello(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

// Tnt_ServiceDesc is the grpc.ServiceDesc for Tnt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tnt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.Tnt",
	HandlerType: (*TntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _Tnt_Insert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Tnt_Get_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _Tnt_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tnt/tnt.proto",
}
